config/routes.rb
Rails.application.routes.draw do

  root 'application#home'
  
  get '/where-to-find', to: 'application#locations', as: 'store_finder'
  get '/team', to: 'application#team', as: 'team'
  mount Spree::Core::Engine, :at => '/products'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home

  end

  def products

  end

  def store_finder
  end

  def team

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<%= render "shared/headerv2" %>
	<section id="slider" class="slider-parallax revslider-wrap clearfix">
		<div class="slider-parallax-inner">

			<div class="tp-banner-container">
				<div class="tp-banner">
					<ul>
						<li class="not-dark" data-transition="slideup" data-slotamount="1" data-masterspeed="1500" data-delay="10000"  data-saveperformance="off">
							<img src="<%= image_path('large/multiple_gummies') %>"  data-bgposition="center bottom" data-kenburns="on" data-duration="10000" data-ease="Linear.easeNone" data-scalestart="100" data-scaleend="120" class="rev-slidebg">
						</li>
						<!-- SLIDE  -->
						<li class="not-dark" data-transition="slideup" data-slotamount="1" data-masterspeed="1500" data-delay="10000"  data-saveperformance="off">
							<img src="<%= image_path('large/laptop_newspaper_hands') %>"  data-bgposition="center bottom" data-kenburns="on" data-duration="10000" data-ease="Linear.easeNone" data-scalestart="100" data-scaleend="120" class="rev-slidebg">
						</li>

						<!-- SLIDE  -->
						<li class="not-dark" data-transition="slideup" data-slotamount="1" data-masterspeed="1500" data-thumb="<%= image_path('large/tropical_juice') %>" data-delay="10000"  data-saveperformance="off">
							<img src="<%= image_path('large/bike_basket') %>"  data-bgposition="center bottom" data-kenburns="on" data-duration="10000" data-ease="Linear.easeNone" data-scalestart="100" data-scaleend="120">
						</li>

						<!-- SLIDE  -->
						<li class="not-dark" data-transition="fade" data-slotamount="1" data-masterspeed="1500" data-thumb="<%= image_path('large/spearmint_juice') %>" data-delay="10000"  data-saveperformance="off">
							<img src="<%= image_path('large/spearmint_juice') %>"  alt="kenburns1"  data-bgposition="center center" data-offsetstart="-250 -100" data-offsetend="250 150" data-bgparallax="2" data-kenburns="on" data-duration="10000" data-ease="Linear.easeNone" data-scalestart="100" data-scaleend="120" data-offsetstart="100 100">
						</li>

					</ul>
				</div>
			</div>

		</div>
		<div class="clear"></div>

	</section>


	<div class="clear"></div>

	<div class="section nomargin noborder">
		<div class="row">
			<div id="asfeaturedtitle" class="heading-block center nobottomborder">
				<h2>As Featured In</h2>
			</div>
			<div class="col-md-2 col-md-offset-1 logo">
				<a href="http://www.forbes.com/sites/forbestreptalks/2016/06/14/this-facebook-alums-gum-startup-is-chewing-off-a-piece-of-cas-2-7b-medical-cannabis-market/#7fd3eeca5884">
					<%= image_tag "external_logos/forbes-logo", class: "center-block" %>
				</a>
			</div>
			<div class="col-md-2 logo">
				<%= image_tag "external_logos/dope-logo", class: "center-block" %>
			</div>
			<div class="col-md-2 logo">
				<%= image_tag "external_logos/high-times-logo", class: "center-block" %>
			</div>
			<div class="col-md-2 logo" id="mg-logo">
				<%= image_tag "external_logos/mg-magazine-logo", class: "center-block" %>
			</div>
			<div class="col-md-2 logo" id="sf-chronicle-logo">
				<a href="http://blog.sfgate.com/smellthetruth/2016/03/03/ten-hot-pot-startups-compete-in-sf-today/">
					<%= image_tag "external_logos/sf-chronicle-logo", class: "center-block" %>
				</a>
			</div>
		</div>
	</div>

		<!-- Content
		============================================= -->
		<section id="content">

			<div class="content-wrap nopadding">

				<div class="section parallax full-screen dark nomargin noborder" style="background-image: url('<%= image_path('large/hand_pack_darkened') %>');" data-stellar-background-ratio="0.4">
					<div class="vertical-middle">
						<div class="container clearfix">

							<div class="row">

								<div class="col-md-4 bottommargin-sm center" data-animate="bounceIn">
									<i class="i-plain i-xlarge divcenter nobottommargin icon-clock"></i>
									<div class="counter counter-large counter-lined"><<span data-from="120" data-to="15" data-refresh-interval="100" data-speed="2000"></span> min</div>
									<h5>Starts working quickly</h5>
								</div>

								<div class="col-md-4 bottommargin-sm center" data-animate="bounceIn" data-delay="200">
									<i class="i-plain i-xlarge divcenter nobottommargin icon-heart"></i>
									<div class="counter counter-large counter-lined"><<span data-from="3000" data-to="5" data-refresh-interval="100" data-speed="1500"></span> cal</div>
									<h5>Guilt free</h5>
								</div>

								<div class="col-md-4 bottommargin-sm center" data-animate="bounceIn" data-delay="400">
									<i class="i-plain i-xlarge divcenter nobottommargin icon-line2-hourglass"></i>
									<div class="counter counter-large counter-lined"><span data-from="1" data-to="4" data-refresh-interval="25" data-speed="2500"></span>+ hrs</div>
									<h5>Effects that last</h5>
								</div>

							</div>

						</div>
					</div>
				</div>

				<div class="section nomargin noborder">
					<div class="heading-block center nobottomborder nobottommargin">
						<h2>#chewplus</h2>
					</div>
				</div>

				<div class="col-md-12 nopadding common-height">

					<div class="col-md-4 dark col-padding ohidden" style="background-color: #1abc9c;">
						<div>
							<h3 class="uppercase" style="font-weight: 600;">Fast Acting, Low Calorie</h3>
							<p style="line-height: 1.8;">THC and CBD are absorbed in your mouth, not your stomach. Plus Gum starts working in less than fifteen minutes and each piece has fewer than five calories.</p>
							<!-- <a href="#" class="button button-border button-light button-rounded uppercase nomargin">Read More</a> -->
							<i class="icon-dashboard bgicon"></i>
						</div>
					</div>

					<div class="col-md-4 dark col-padding ohidden" style="background-color: #34495e;">
						<div>
							<h3 class="uppercase" style="font-weight: 600;">Healthy Ingredients</h3>
							<p style="line-height: 1.8;">We use only the highest quality extracts to make Plus Gum. Both our active and inactive ingredients are sourced from the best suppliers we can find. Every batch is tested by two independent labs.</p>
							<!-- <a href="#" class="button button-border button-light button-rounded uppercase nomargin">Read More</a> -->
							<i class="icon-cog bgicon"></i>
						</div>
					</div>

					<div class="col-md-4 dark col-padding ohidden" style="background-color: #e74c3c;">
						<div>
							<h3 class="uppercase" style="font-weight: 600;">Great Flavor</h3>
							<p style="line-height: 1.8;">We leave only a small hint of cannabis in Plus Gum. Enough so you know it's working, but your senses aren't overloaded.</p>
							<!-- <a href="#" class="button button-border button-light button-rounded uppercase nomargin">Read More</a> -->
							<i class="icon-thumbs-up bgicon"></i>
						</div>
					</div>

					<div class="clear"></div>

				</div>
				<div class="clear"></div>

				<div class="section parallax full-screen nomargin noborder" style="background-image: url('<%= image_path('large/bike_basket_lightened') %>');" data-stellar-background-ratio="0.4">
					<div class="vertical-middle">
						<div class="container clearfix">

							<div class="col_three_fifth nobottommargin">

								<div class="emphasis-title">
									<h2>Tastes <strong>like gum</strong></h2>
									<p class="lead topmargin-sm hidden-xs hidden-s">You shouldn't have to compromise. Plus Gum is fast acting <i>and</i> tastes great.</p>
								</div>

							</div>

						</div>
					</div>
				</div>



				<div class="clear"></div>

				<div class="section nomargin noborder">
					<div class="heading-block center nobottomborder nobottommargin">
						<h2>"This is the best edible I have ever had."</h2>
					</div>
				</div>

				<div id="instagram-photos" class="instagram-photos masonry-thumbs col-5" data-user="2032193147" data-count="10" data-type="user" data-resolution="standard_resolution"></div>
		</section><!-- #content end -->

app/views/application/locations.html.erb
<%= render "shared/headerv2" %>
<div class="section parallax dark nomargin noborder" style="background-image: url('<%= image_path('large/hand_pack_darkened') %>'); height: 280px;" data-stellar-background-ratio="0.4">
          <div class="vertical-middle">
            <div class="container clearfix">
              <div class="row">
                <div class="col-md-12 bottommargin-sm center" data-animate="bounceIn" data-delay="200">
                  <br>
                  <br>
                  <br>
                  <h2>FIND OUT WHERE YOU CAN BUY <span class="plusgum-color">PLUS GUM</span> AND <span class="plusgum-color">GUMMIES</span> NEAR YOU.</h2>
                </div>
              </div>
            </div>
          </div>
        </div>

<div class="container">
  <div class="row text-left map-styling">
    <div class="col-lg-9">
      <div id="storelocatorwidget" style="width:100%;"><p>Loading <a href="https://www.storelocatorwidgets.com">Store Locator Software</a>...</p></div>
      <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=AIzaSyB6pFYTjVinTStepzUJEhX2KHUQlstM260&libraries=places"></script>
      <script type="text/javascript" id="storelocatorscript" data-uid="2551cc811f3de80b4b0ab2d8eb252ec6" src="//cdn.storelocatorwidgets.com/widget/widget.js"></script>
    </div>
    <div class="col-lg-3 side-column text-center">
      <hr>
      <h3 class="title-styling">LOCAL STORE NOT ON THE MAP?</h3>
      <p class="smalltext">Simply drop off a product request form the next time you go shopping.</p>
      <a href="<%= image_path('Plus Products Request Form.pdf') %>"><div class="side-button">PRODUCT REQUEST FORM</div></a>
      <h3 class="title-styling">NOT IN CALIFORNIA?</h3>
      <p class="smalltext">Join our mailing list for awesome goodies and to know when Plus becomes available in your state.</p>

      <!-- Begin MailChimp Signup Form -->
      <div id="mc_embed_signup">
        <form action="//plusgum.us13.list-manage.com/subscribe/post?u=20a1032c6c24d2f6fd11665f3&amp;id=c9f0814e1f" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
          <div id="mc_embed_signup_scroll">
            <h2></h2>
            <div class="mc-field-group">
              <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="Enter your email">
            </div>
            <div id="mce-responses" class="clear">
              <div class="response" id="mce-error-response" style="display:none"></div>
              <div class="response" id="mce-success-response" style="display:none"></div>
            </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_20a1032c6c24d2f6fd11665f3_c9f0814e1f" tabindex="-1" value=""></div>
            <br>
            <div class=""><input class="side-button submit-button" type="submit" value="SUBSCRIBE TO NEWSLETTER" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
          </div>
        </form>
      </div>

      <!--End mc_embed_signup-->


      <hr>
    </div>
  </div>
</div>
<div class="section parallax dark nomargin noborder" style="background-image: url('<%= image_path('large/hand_pack_darkened') %>'); height: 300px;" data-stellar-background-ratio="0.4">
</div>
<div class="heading-block center nobottomborder nobottommargin"></div>
<div class="section nomargin noborder">
  <div class="heading-block center nobottomborder nobottommargin">
    <h2>Follow us on instagram @plus_gum</h2>
  </div>
</div>

<div id="instagram-photos" class="instagram-photos masonry-thumbs col-5" data-user="2032193147" data-count="10" data-type="user" data-resolution="standard_resolution"></div>

app/views/application/products.html.erb
<%= render "shared/headerv2" %>

<div class="section nomargin noborder">
  <div class="heading-block center nobottomborder nobottommargin">
    <h2>products</h2>
  </div>
</div>

<div id="products" class="portfolio grid-container portfolio-nomargin portfolio-full portfolio-masonry mixed-masonry grid-container clearfix">

  <article class="portfolio-item pf-media pf-icons wide">
    <div class="portfolio-image">
      <%= image_tag "products/sour_tin" %>
      <div class="portfolio-overlay">
        <div class="portfolio-desc">
          <h3>Sour Gummies</h3>
          <span>200mg THC</span>
        </div>
        <a href="<%= image_path "products/sour_tin" %>" class="left-icon" data-lightbox="image"><i class="icon-line-plus"></i></a>
      </div>
    </div>
  </article>

  <article class="portfolio-item pf-media pf-icons wide">
    <div class="portfolio-image">
      <%= image_tag "products/original_tin" %>
      <div class="portfolio-overlay">
        <div class="portfolio-desc">
          <h3>Original Gummies</h3>
          <span>200mg THC</span>
        </div>
        <a href="<%= image_path "products/original_tin" %>" class="left-icon" data-lightbox="image"><i class="icon-line-plus"></i></a>
      </div>
    </div>
  </article>

  <article class="portfolio-item pf-media pf-icons wide">
    <div class="portfolio-image">
      <%= image_tag "products/spearmint_sixpack" %>
      <div class="portfolio-overlay">
        <div class="portfolio-desc">
          <h3> Spearmint Six Pack</h3>
          <span>150mg THC total, 25mg per piece</span>
        </div>
        <a href="<%= image_path "products/spearmint_sixpack" %>" class="left-icon" data-lightbox="image"><i class="icon-line-plus"></i></a>
      </div>
    </div>
  </article>

  <article class="portfolio-item pf-media pf-icons wide">
    <div class="portfolio-image">
      <%= image_tag "products/spearmint_single" %>
      <div class="portfolio-overlay">
        <div class="portfolio-desc">
          <h3> Spearmint Single</h3>
          <span>25mg THC</span>
        </div>
        <a href="<%= image_path "products/spearmint_single" %>" class="left-icon" data-lightbox="image"><i class="icon-line-plus"></i></a>
      </div>
    </div>
  </article>
  
</div>

<div class="section nomargin noborder">
  <div class="heading-block center nobottomborder nobottommargin">
    <h2><%= link_to "Find Plus Gum near you", store_finder_path %></h2>
  </div>
</div>

<div class="section parallax full-screen nomargin noborder dark" style="background-image: url('<%= image_path('large/hands_plus') %>');" data-stellar-background-ratio="0.4">
</div>

<div class="section nomargin noborder">
  <div class="heading-block center nobottomborder nobottommargin">
    <h2>"I can't believe how quickly it worked."</h2>
  </div>
</div>
<div id="instagram-photos" class="instagram-photos masonry-thumbs col-5" data-user="2032193147" data-count="10" data-type="user" data-resolution="standard_resolution"></div>

app/views/application/team.html.erb
<%= render "shared/headerv2" %>

<div class="section parallax full-screen nomargin noborder dark" style="background-image: url('<%= image_path('plus_team') %>');" data-stellar-background-ratio="0.4">
  <div class="vertical-middle">
    <div class="container clearfix">

      <div class="col_three_fifth nobottommargin hidden-xs">

        <div class="emphasis-title">
          <h2>We are what we eat</h2>
          <p class="lead topmargin-sm">At Plus, we believe that everyone deserves access to effective, high quality medication made from the best ingredients.</p>
        </div>

      </div>

    </div>
  </div>
</div>


<div id="team" class="section nomargin noborder">
  <div class="heading-block center nobottomborder nobottommargin">
    <h2>team</h2>
  </div>
</div>

<div class="clear"></div>

<div class="row">

  <div class="col-md-3 col-sm-6 bottommargin">

    <div class="team">
      <div class="team-image">
        <%= image_tag "jake" %>
      </div>
      <div class="team-desc">
        <div class="team-title"><h4>Jake</h4><span>CEO</span></div>
      </div>
    </div>

  </div>

  <div class="col-md-3 col-sm-6 bottommargin">

    <div class="team">
      <div class="team-image">
        <%= image_tag "crunchy" %>
      </div>
      <div class="team-desc">
        <div class="team-title"><h4>Crunchy</h4><span>Science</span></div>
      </div>
    </div>

  </div>

  <div class="col-md-3 col-sm-6 bottommargin">

    <div class="team">
      <div class="team-image">
        <%= image_tag "roy" %>
      </div>
      <div class="team-desc">
        <div class="team-title"><h4>Roy</h4><span>Operations</span></div>
      </div>
    </div>

  </div>

  <div class="col-md-3 col-sm-6 bottommargin">

    <div class="team">
      <div class="team-image">
        <%= image_tag "lucie" %>
      </div>
      <div class="team-desc">
        <div class="team-title"><h4>Lucie</h4><span>Sales</span></div>
      </div>

    </div>

  </div>
</div>

<div class="section parallax full-screen nomargin noborder dark" style="background-image: url('<%= image_path('large/tea_plus') %>');" data-stellar-background-ratio="0.4">
  <div class="vertical-middle">
    <div class="heading-block center nobottomborder nobottommargin">
      <h1>#mydailyroutine</h1>
    </div>
  </div>
</div>

<div class="section nomargin noborder">
  <div class="heading-block center nobottomborder nobottommargin">
    <h2>"Where can I get more? I need it. I can't go back to other edibles"</h2>
  </div>
</div>
<div id="instagram-photos" class="instagram-photos masonry-thumbs col-5" data-user="2032193147" data-count="10" data-type="user" data-resolution="standard_resolution"></div>

app/views/application/where.html.erb
<%= render "shared/headerv2" %>

<div class="section nomargin noborder">
  <div class="heading-block center nobottomborder nobottommargin">
    <h2>where</h2>
  </div>
</div>

<div class="section parallax full-screen nomargin noborder dark" style="background-image: url('<%= image_path('large/hands_plus') %>');" data-stellar-background-ratio="0.4">
</div>

<div class="section nomargin noborder">
  <div class="heading-block center nobottomborder nobottommargin">
    <h2>"I can't believe how quickly it worked."</h2>
  </div>
</div>
<div id="instagram-photos" class="instagram-photos masonry-thumbs col-5" data-user="2032193147" data-count="10" data-type="user" data-resolution="standard_resolution"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plusproductsdotcom</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer">

  <div class="container footer-mid">
    <div class="row">
      <div class="col-sm-4 footer-col">
        <h4>ABOUT THE GUM</h4>
        <ul>
          <li><%= link_to "Fast Acting",  main_app.about_gum_path(anchor: 'fast-acting') %></li>
          <li><%= link_to "Low Calorie", main_app.about_gum_path(anchor: 'low-calorie') %></li>
          <li><%= link_to "Tastes Great", main_app.about_gum_path(anchor: 'great-flavor') %></li>
        </ul>
      </div>
      <div class="col-sm-4 footer-col">
        <h4>ABOUT THE COMPANY</h4>
        <ul>
          <li><%= link_to "Team", main_app.about_company_path %></li>
          <li><%= link_to "Jobs", 'https://angel.co/plus-gum/jobs/', target: '_blank' %></li>
        </ul>
      </div>
      <div class="col-sm-4 footer-col">
        <h4>CONTACT US</h4>
        <ul>
          <li>
            <a href="mailto:hi@plusgum.com" target="_blank">
              <i class="fa fa-envelope left"></i>
              <span> hi@plusgum.com</span>
            </a>
          </li>
          <li>
            <a onclick="Intercom('show')">
              <i class="fa fa-comment left"></i> Chat With Us</i>
            </a>
          </li>
          <li id="phonenumber">
            <a href="tel:+18005640842">
              <i class="fa fa-phone left"></i>
              <span>1 (800) 564-0842</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>


  <div class="footer-terminal">
    <div class="container">
      <p id="prepared">PLUS GUM IS ARTFULLY PREPARED IN THE BAY AREA</p>
      <ul class="pull-right">
        <li id="copyright">© 2015 PLUS MEDICAL</li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_footerv2.html.erb
<footer id="footer" class="dark">



  <!-- Copyrights
  ============================================= -->
  <div id="copyrights">

    <div class="container clearfix">

      <div class="col_half">
        Copyrights &copy; 2016 All Rights Reserved by Plus<br>
      </div>

      <div class="col_half col_last tright">
        <div class="fright clearfix">
          <a href="https://instagram.com/plus_gum" class="social-icon si-small si-borderless si-instagram">
            <i class="icon-instagram"></i>
            <i class="icon-instagram"></i>
          </a>

          <a href="https://www.facebook.com/chewplus" class="social-icon si-small si-borderless si-facebook">
            <i class="icon-facebook"></i>
            <i class="icon-facebook"></i>
          </a>

          <a href="https://twitter.com/plus_gum" class="social-icon si-small si-borderless si-twitter">
            <i class="icon-twitter"></i>
            <i class="icon-twitter"></i>
          </a>
        </div>

        <div class="clear"></div>

        <a href="mailto:hi@plusgum.com" target="_blank"><i class="icon-envelope2"></i> hi@plusgum.com </a><span class="middot">&middot;</span> <a href="tel:+18005640842"><i class="icon-headphones"></i> +1 (800) 564-0842 </a><span class="middot">&middot;</span> <a onclick="Intercom('show')"><i class="icon-comment"></i> Chat With Us</a>
      </div>

    </div>

  </div><!-- #copyrights end -->

</footer><!-- #footer end -->

app/views/shared/_head.html.erb
<title><%= yield(:title).empty? ? "Plus" : yield(:title) %></title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<%= analytics_init if Rails.env.production? %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<% if @mobile_viewport %>
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<% else %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
<% end %>
<%= favicon_link_tag 'favicon.ico' %>
<link href='https://fonts.googleapis.com/css?family=Roboto:300,400,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:700' rel='stylesheet' type='text/css'>

app/views/shared/_headerv2.html.erb
<!-- Header
============================================= -->
<header id="header" class="transparent-header full-header">

  <div id="header-wrap">

    <div class="container clearfix">

      <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

      <!-- Logo
      ============================================= -->
      <div id="logo">
        <a href="/" class="standard-logo" data-dark-logo="<%= image_path('logo/logo_dark') %>">
          <%= image_tag "logo/logo", alt: "Plus Logo" %>
        </a>
        <a href="/" class="retina-logo" data-dark-logo="<%= image_path('logo/logo_dark@2x')%>">
          <%= image_tag "logo/logo@2x", alt: "Plus Logo" %>
        </a>
      </div><!-- #logo end -->

      <!-- Primary Navigation
      ============================================= -->
      <nav id="primary-menu">
        <ul>
          <li class="<%= 'current' if current_page?(root_path) %>">
            <%= link_to "Home", root_path %>
          </li>
          <li class="<%= 'current' if current_page?(spree_path) %>">
            <%= link_to "Products", spree_path %>
          </li>
          <li class="<%= 'current' if current_page?(store_finder_path) %>">
            <%= link_to "Locations", store_finder_path %>
          </li>
          <li class="<%= 'current' if current_page?(team_path) %>">
            <%= link_to "Team", team_path %>
          </li>
        </ul>
      </nav><!-- #primary-menu end -->

    </div>

  </div>

</header><!-- #header end -->

app/views/shared/_headv2.html.erb
<title><%= yield(:title).empty? ? "Plus" : yield(:title) %></title>
<%= stylesheet_link_tag 'applicationv2', media: 'all' %>
<%= analytics_init if Rails.env.production? %>
<%= csrf_meta_tags %>
<% if @mobile_viewport %>
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<% else %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
<% end %>
<%= favicon_link_tag 'favicon.ico' %>
<link href='https://fonts.googleapis.com/css?family=Roboto:300,400,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:700' rel='stylesheet' type='text/css'>
<link href="https://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
<!--[if lt IE 9]>
  <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
<meta property="og:title" content="Plus Cannabis Infused Gum" />
<meta property="og:description" content="Gluten free, vegan friendly and with no artificial sweeteners — Plus Gum is absorbed in your mouth, not your stomach, so it starts working in less than fifteen minutes. Each piece has fewer than five calories." />
<meta property="og:image" content="<%= image_url('products/spearmint_sixpack_thumb')%>" />

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">

  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%= image_tag "plus_white" %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ABOUT THE GUM", main_app.about_gum_path %></li>
        <li><%= link_to "OUR TEAM", main_app.about_company_path %></li>
          <li><%= link_to "WHERE TO BUY", main_app.store_finder_path %></li>
      </ul>
    </div>

  </div>

</nav>